---
- name: Ensure certs directory exists
  become: true
  file:
    path: "{{ ssl_certs_dir }}"
    state: directory

- name: Create private key
  become: true
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key_filename }}"

- name: Create simple self-signed certificate
  become: true
  community.crypto.x509_certificate:
    path: "{{ ssl_cert_filename }}"
    privatekey_path: "{{ ssl_key_filename }}"
    provider: selfsigned
