- name: Install python-debian
  package:
    name: python-debian
    state: latest

- name: Add repo grafana
  yum_repository:
    name: grafana
    description: Grafana Repo
    baseurl: https://rpm.grafana.com
    gpgcheck: yes
    gpgkey: https://rpm.grafana.com/gpg.key

- name: Install base software packages
  package:
    name:
      - curl
      - git
      - kitty-terminfo
      - tmux
      - vim
      - acl
      - jq
      - rsync
      - node-exporter
      - alloy
    state: latest
