- name: Add Grafana apt repo
  ansible.builtin.deb822_repository:
    name: grafana
    types: deb
    uris: https://apt.grafana.com
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://apt.grafana.com/gpg.key

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Update all Debian/Ubuntu packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install base software packages
  package:
    name:
      - curl
      - git
      - kitty-terminfo
      - tmux
      - vim
      - acl
      - iputils-ping
      - jq
      - rsync
      - prometheus-node-exporter
      - prometheus-node-exporter-collectors
      - alloy
    state: latest
