# ─────────────────────────────────────────────────────────
# canton-test-01: All-in-one Zenith-Canton deployment
# ─────────────────────────────────────────────────────────

# Sequencer-Mediator ports
canton_sequencer_mediator_config: sequencer-mediator.conf
canton_sequencer_public_api_port: 5008
canton_sequencer_admin_api_port: 5009
canton_mediator_admin_api_port: 5007

# All services on this host (for Vector / monitoring)
canton_services:
  - name: canton-postgres
    type: postgres
  - name: canton-sequencer-mediator
    type: sequencer-mediator
  - name: canton-participant1
    type: participant
  - name: canton-participant2
    type: participant
  - name: canton-participant3
    type: participant
  - name: canton-network-setup
    type: setup
  - name: zenith-deploy-contract
    type: setup
  - name: zenith-block-builder-1
    type: block-builder
  - name: zenith-block-builder-2
    type: block-builder
  - name: zenith-ecs-1
    type: ecs
  - name: zenith-ecs-2
    type: ecs
  - name: canton-evm-explorer-indexer
    type: explorer
  - name: canton-evm-explorer
    type: explorer
  - name: zenith-headcaster-1
    type: headcaster
  - name: zenith-sequencer-1
    type: sequencer
  - name: cloudflared
    type: tunnel
