galaxy_info:
  author: gevulot
  description: Canton PostgreSQL via Podman (user service)
  company: Gevulot
  license: GPL-2.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm

dependencies: []
