- name: Debug input variables
  debug:
    var: github_pat

- name: Make sure binaries destination exists
  file:
    path: "{{ binary_destination }}"
    state: directory

- name: "Download infra-tools binaries"
  include_tasks: download.yml
  loop: "{{ binaries }}"
  loop_control:
    loop_var: binary
  vars:
    owner: "gevulotnetwork"
    repo: "infra-tools"
    destination: "{{ binary_destination }}"
    pat_token: "{{ github_pat }}"
  when: binaries is defined

- name: Create deployd systemd unit
  vars:
    service:
      description: "deployd service"
      binary: "/opt/bin/deployd"
  template:
    src: templates/service.j2
    dest: /lib/systemd/system/deployd.service
