galaxy_info:
  author: gevulot
  description: Canton network topology setup service
  company: Gevulot
  license: GPL-2.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm

dependencies: []
