- name: ensure firewalld is running
  ansible.builtin.systemd_service:
    enabled: true
    name: firewalld
    state: started

- name: Allow SSH
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
    offline: true
  loop:
    - ssh
    - http
    - https
