canton_postgres_user: canton
canton_postgres_password: canton
canton_postgres_port: 5432
canton_postgres_image: "docker.io/postgres:15"
canton_postgres_max_connections: 1000
canton_postgres_tcp_keepalives_idle: 60
canton_postgres_tcp_keepalives_interval: 10
canton_postgres_tcp_keepalives_count: 6
canton_postgres_databases:
  - sequencer1
  - mediator1
  - participant1
  - participant2
  - participant3
  - canton_evm_explorer
