dependencies: []

galaxy_info:
  role_name: gevulot_software
  author: bhechinger
  description: Gevulot specific software for instances
  company: "Gevulot"
  license: "Do Not Redistribute"
  min_ansible_version: 2.15
