- name: Reload user systemd
  become: true
  become_user: "{{ canton_user }}"
  ansible.builtin.command:
    cmd: systemctl --user daemon-reload
  changed_when: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ canton_uid.stdout }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ canton_uid.stdout }}/bus"

- name: Restart canton-sequencer-mediator
  become: true
  become_user: "{{ canton_user }}"
  ansible.builtin.command:
    cmd: systemctl --user restart canton-sequencer-mediator
  changed_when: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ canton_uid.stdout }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ canton_uid.stdout }}/bus"
