dependencies: []

galaxy_info:
  role_name: wait_for_cloud_init
  author: bhechinger
  description: Wait for cloud-init to complete
  company: "Gevulot"
  license: "Do Not Redistribute"
  min_ansible_version: 2.15
