- name: Copy Canton JAR
  ansible.builtin.copy:
    src: "{{ canton_dist_dir }}/canton.jar"
    dest: "{{ canton_lib_dir }}/canton.jar"
    owner: "{{ canton_user }}"
    group: "{{ canton_group }}"
    mode: "0644"
  register: canton_jar_deployed

- name: Create damlc directory
  ansible.builtin.file:
    path: "{{ canton_bin_dir }}/damlc"
    state: directory
    owner: "{{ canton_user }}"
    group: "{{ canton_group }}"
    mode: "0755"

- name: Extract damlc
  ansible.builtin.unarchive:
    src: "{{ canton_dist_dir }}/damlc.tar.gz"
    dest: "{{ canton_bin_dir }}/damlc"
    owner: "{{ canton_user }}"
    group: "{{ canton_group }}"
    creates: "{{ canton_bin_dir }}/damlc/bazel-bin/compiler/damlc/damlc-bootstrap"

- name: Deploy Zenith DAR files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ canton_dars_dir }}/{{ item | basename }}"
    owner: "{{ canton_user }}"
    group: "{{ canton_group }}"
    mode: "0644"
  loop:
    - "{{ canton_dist_dir }}/zenith-bridge.dar"
  register: canton_dar_deployed

- name: Deploy EVM contract files
  ansible.builtin.copy:
    src: "{{ canton_dist_dir }}/{{ item }}"
    dest: "{{ zenith_etc_dir }}/{{ item }}"
    owner: "{{ canton_user }}"
    group: "{{ canton_group }}"
    mode: "0644"
  loop:
    - BridgedToken.bin
    - BridgedToken.json
